version: '3.9'

services:
  web:
    build: ./api_with_restrictions
    command: gunicorn api_with_restrictions.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/api_with_restrictions/static
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - api_with_restrictions/.env
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/html/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: